name: Build Godot Project
on:
  release:
    types: [released]
env:
  GODOT_VERSION: 4.2.1
  NAME: letscraft

jobs:
  build-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.2.1
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      
    - name: Setup
      run: |
        mkdir -v -p build/linux ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/template/${GODOT_VERSION}.stable
        
    - name: Build
      run: godot -v --export "Linux/X11" ./build/linux/${NAME}.x86_64
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: ./build/linux/
      
